/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TaxRateService } from "../taxRate.service";
import { TaxRateCreateInput } from "./TaxRateCreateInput";
import { TaxRate } from "./TaxRate";
import { TaxRateFindManyArgs } from "./TaxRateFindManyArgs";
import { TaxRateWhereUniqueInput } from "./TaxRateWhereUniqueInput";
import { TaxRateUpdateInput } from "./TaxRateUpdateInput";

export class TaxRateControllerBase {
  constructor(protected readonly service: TaxRateService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaxRate })
  async createTaxRate(
    @common.Body() data: TaxRateCreateInput
  ): Promise<TaxRate> {
    return await this.service.createTaxRate({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TaxRate] })
  @ApiNestedQuery(TaxRateFindManyArgs)
  async taxRates(@common.Req() request: Request): Promise<TaxRate[]> {
    const args = plainToClass(TaxRateFindManyArgs, request.query);
    return this.service.taxRates({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaxRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async taxRate(
    @common.Param() params: TaxRateWhereUniqueInput
  ): Promise<TaxRate | null> {
    const result = await this.service.taxRate({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaxRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTaxRate(
    @common.Param() params: TaxRateWhereUniqueInput,
    @common.Body() data: TaxRateUpdateInput
  ): Promise<TaxRate | null> {
    try {
      return await this.service.updateTaxRate({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaxRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTaxRate(
    @common.Param() params: TaxRateWhereUniqueInput
  ): Promise<TaxRate | null> {
    try {
      return await this.service.deleteTaxRate({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
