/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TaxRate } from "./TaxRate";
import { TaxRateCountArgs } from "./TaxRateCountArgs";
import { TaxRateFindManyArgs } from "./TaxRateFindManyArgs";
import { TaxRateFindUniqueArgs } from "./TaxRateFindUniqueArgs";
import { DeleteTaxRateArgs } from "./DeleteTaxRateArgs";
import { TaxRateService } from "../taxRate.service";
@graphql.Resolver(() => TaxRate)
export class TaxRateResolverBase {
  constructor(protected readonly service: TaxRateService) {}

  async _taxRatesMeta(
    @graphql.Args() args: TaxRateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TaxRate])
  async taxRates(
    @graphql.Args() args: TaxRateFindManyArgs
  ): Promise<TaxRate[]> {
    return this.service.taxRates(args);
  }

  @graphql.Query(() => TaxRate, { nullable: true })
  async taxRate(
    @graphql.Args() args: TaxRateFindUniqueArgs
  ): Promise<TaxRate | null> {
    const result = await this.service.taxRate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaxRate)
  async deleteTaxRate(
    @graphql.Args() args: DeleteTaxRateArgs
  ): Promise<TaxRate | null> {
    try {
      return await this.service.deleteTaxRate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
