/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TaxRate as PrismaTaxRate } from "@prisma/client";

export class TaxRateServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TaxRateCountArgs, "select">): Promise<number> {
    return this.prisma.taxRate.count(args);
  }

  async taxRates(args: Prisma.TaxRateFindManyArgs): Promise<PrismaTaxRate[]> {
    return this.prisma.taxRate.findMany(args);
  }
  async taxRate(
    args: Prisma.TaxRateFindUniqueArgs
  ): Promise<PrismaTaxRate | null> {
    return this.prisma.taxRate.findUnique(args);
  }
  async createTaxRate(args: Prisma.TaxRateCreateArgs): Promise<PrismaTaxRate> {
    return this.prisma.taxRate.create(args);
  }
  async updateTaxRate(args: Prisma.TaxRateUpdateArgs): Promise<PrismaTaxRate> {
    return this.prisma.taxRate.update(args);
  }
  async deleteTaxRate(args: Prisma.TaxRateDeleteArgs): Promise<PrismaTaxRate> {
    return this.prisma.taxRate.delete(args);
  }
}
