/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StockEntryService } from "../stockEntry.service";
import { StockEntryCreateInput } from "./StockEntryCreateInput";
import { StockEntry } from "./StockEntry";
import { StockEntryFindManyArgs } from "./StockEntryFindManyArgs";
import { StockEntryWhereUniqueInput } from "./StockEntryWhereUniqueInput";
import { StockEntryUpdateInput } from "./StockEntryUpdateInput";

export class StockEntryControllerBase {
  constructor(protected readonly service: StockEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StockEntry })
  async createStockEntry(
    @common.Body() data: StockEntryCreateInput
  ): Promise<StockEntry> {
    return await this.service.createStockEntry({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [StockEntry] })
  @ApiNestedQuery(StockEntryFindManyArgs)
  async stockEntries(@common.Req() request: Request): Promise<StockEntry[]> {
    const args = plainToClass(StockEntryFindManyArgs, request.query);
    return this.service.stockEntries({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StockEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stockEntry(
    @common.Param() params: StockEntryWhereUniqueInput
  ): Promise<StockEntry | null> {
    const result = await this.service.stockEntry({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StockEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStockEntry(
    @common.Param() params: StockEntryWhereUniqueInput,
    @common.Body() data: StockEntryUpdateInput
  ): Promise<StockEntry | null> {
    try {
      return await this.service.updateStockEntry({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StockEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStockEntry(
    @common.Param() params: StockEntryWhereUniqueInput
  ): Promise<StockEntry | null> {
    try {
      return await this.service.deleteStockEntry({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
