/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StockEntry } from "./StockEntry";
import { StockEntryCountArgs } from "./StockEntryCountArgs";
import { StockEntryFindManyArgs } from "./StockEntryFindManyArgs";
import { StockEntryFindUniqueArgs } from "./StockEntryFindUniqueArgs";
import { DeleteStockEntryArgs } from "./DeleteStockEntryArgs";
import { StockEntryService } from "../stockEntry.service";
@graphql.Resolver(() => StockEntry)
export class StockEntryResolverBase {
  constructor(protected readonly service: StockEntryService) {}

  async _stockEntriesMeta(
    @graphql.Args() args: StockEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StockEntry])
  async stockEntries(
    @graphql.Args() args: StockEntryFindManyArgs
  ): Promise<StockEntry[]> {
    return this.service.stockEntries(args);
  }

  @graphql.Query(() => StockEntry, { nullable: true })
  async stockEntry(
    @graphql.Args() args: StockEntryFindUniqueArgs
  ): Promise<StockEntry | null> {
    const result = await this.service.stockEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StockEntry)
  async deleteStockEntry(
    @graphql.Args() args: DeleteStockEntryArgs
  ): Promise<StockEntry | null> {
    try {
      return await this.service.deleteStockEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
