/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, StockEntry as PrismaStockEntry } from "@prisma/client";

export class StockEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.StockEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.stockEntry.count(args);
  }

  async stockEntries(
    args: Prisma.StockEntryFindManyArgs
  ): Promise<PrismaStockEntry[]> {
    return this.prisma.stockEntry.findMany(args);
  }
  async stockEntry(
    args: Prisma.StockEntryFindUniqueArgs
  ): Promise<PrismaStockEntry | null> {
    return this.prisma.stockEntry.findUnique(args);
  }
  async createStockEntry(
    args: Prisma.StockEntryCreateArgs
  ): Promise<PrismaStockEntry> {
    return this.prisma.stockEntry.create(args);
  }
  async updateStockEntry(
    args: Prisma.StockEntryUpdateArgs
  ): Promise<PrismaStockEntry> {
    return this.prisma.stockEntry.update(args);
  }
  async deleteStockEntry(
    args: Prisma.StockEntryDeleteArgs
  ): Promise<PrismaStockEntry> {
    return this.prisma.stockEntry.delete(args);
  }
}
