/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkstationService } from "../workstation.service";
import { WorkstationCreateInput } from "./WorkstationCreateInput";
import { Workstation } from "./Workstation";
import { WorkstationFindManyArgs } from "./WorkstationFindManyArgs";
import { WorkstationWhereUniqueInput } from "./WorkstationWhereUniqueInput";
import { WorkstationUpdateInput } from "./WorkstationUpdateInput";

export class WorkstationControllerBase {
  constructor(protected readonly service: WorkstationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Workstation })
  async createWorkstation(
    @common.Body() data: WorkstationCreateInput
  ): Promise<Workstation> {
    return await this.service.createWorkstation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Workstation] })
  @ApiNestedQuery(WorkstationFindManyArgs)
  async workstations(@common.Req() request: Request): Promise<Workstation[]> {
    const args = plainToClass(WorkstationFindManyArgs, request.query);
    return this.service.workstations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Workstation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async workstation(
    @common.Param() params: WorkstationWhereUniqueInput
  ): Promise<Workstation | null> {
    const result = await this.service.workstation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Workstation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWorkstation(
    @common.Param() params: WorkstationWhereUniqueInput,
    @common.Body() data: WorkstationUpdateInput
  ): Promise<Workstation | null> {
    try {
      return await this.service.updateWorkstation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Workstation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWorkstation(
    @common.Param() params: WorkstationWhereUniqueInput
  ): Promise<Workstation | null> {
    try {
      return await this.service.deleteWorkstation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
