/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SalesOrderService } from "../salesOrder.service";
import { SalesOrderCreateInput } from "./SalesOrderCreateInput";
import { SalesOrder } from "./SalesOrder";
import { SalesOrderFindManyArgs } from "./SalesOrderFindManyArgs";
import { SalesOrderWhereUniqueInput } from "./SalesOrderWhereUniqueInput";
import { SalesOrderUpdateInput } from "./SalesOrderUpdateInput";

export class SalesOrderControllerBase {
  constructor(protected readonly service: SalesOrderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalesOrder })
  async createSalesOrder(
    @common.Body() data: SalesOrderCreateInput
  ): Promise<SalesOrder> {
    return await this.service.createSalesOrder({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SalesOrder] })
  @ApiNestedQuery(SalesOrderFindManyArgs)
  async salesOrders(@common.Req() request: Request): Promise<SalesOrder[]> {
    const args = plainToClass(SalesOrderFindManyArgs, request.query);
    return this.service.salesOrders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalesOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async salesOrder(
    @common.Param() params: SalesOrderWhereUniqueInput
  ): Promise<SalesOrder | null> {
    const result = await this.service.salesOrder({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalesOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSalesOrder(
    @common.Param() params: SalesOrderWhereUniqueInput,
    @common.Body() data: SalesOrderUpdateInput
  ): Promise<SalesOrder | null> {
    try {
      return await this.service.updateSalesOrder({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalesOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSalesOrder(
    @common.Param() params: SalesOrderWhereUniqueInput
  ): Promise<SalesOrder | null> {
    try {
      return await this.service.deleteSalesOrder({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
