/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PayrollRunService } from "../payrollRun.service";
import { PayrollRunCreateInput } from "./PayrollRunCreateInput";
import { PayrollRun } from "./PayrollRun";
import { PayrollRunFindManyArgs } from "./PayrollRunFindManyArgs";
import { PayrollRunWhereUniqueInput } from "./PayrollRunWhereUniqueInput";
import { PayrollRunUpdateInput } from "./PayrollRunUpdateInput";

export class PayrollRunControllerBase {
  constructor(protected readonly service: PayrollRunService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PayrollRun })
  async createPayrollRun(
    @common.Body() data: PayrollRunCreateInput
  ): Promise<PayrollRun> {
    return await this.service.createPayrollRun({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PayrollRun] })
  @ApiNestedQuery(PayrollRunFindManyArgs)
  async payrollRuns(@common.Req() request: Request): Promise<PayrollRun[]> {
    const args = plainToClass(PayrollRunFindManyArgs, request.query);
    return this.service.payrollRuns({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PayrollRun })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async payrollRun(
    @common.Param() params: PayrollRunWhereUniqueInput
  ): Promise<PayrollRun | null> {
    const result = await this.service.payrollRun({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PayrollRun })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePayrollRun(
    @common.Param() params: PayrollRunWhereUniqueInput,
    @common.Body() data: PayrollRunUpdateInput
  ): Promise<PayrollRun | null> {
    try {
      return await this.service.updatePayrollRun({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PayrollRun })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePayrollRun(
    @common.Param() params: PayrollRunWhereUniqueInput
  ): Promise<PayrollRun | null> {
    try {
      return await this.service.deletePayrollRun({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
