/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PayrollRun as PrismaPayrollRun } from "@prisma/client";

export class PayrollRunServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PayrollRunCountArgs, "select">
  ): Promise<number> {
    return this.prisma.payrollRun.count(args);
  }

  async payrollRuns(
    args: Prisma.PayrollRunFindManyArgs
  ): Promise<PrismaPayrollRun[]> {
    return this.prisma.payrollRun.findMany(args);
  }
  async payrollRun(
    args: Prisma.PayrollRunFindUniqueArgs
  ): Promise<PrismaPayrollRun | null> {
    return this.prisma.payrollRun.findUnique(args);
  }
  async createPayrollRun(
    args: Prisma.PayrollRunCreateArgs
  ): Promise<PrismaPayrollRun> {
    return this.prisma.payrollRun.create(args);
  }
  async updatePayrollRun(
    args: Prisma.PayrollRunUpdateArgs
  ): Promise<PrismaPayrollRun> {
    return this.prisma.payrollRun.update(args);
  }
  async deletePayrollRun(
    args: Prisma.PayrollRunDeleteArgs
  ): Promise<PrismaPayrollRun> {
    return this.prisma.payrollRun.delete(args);
  }
}
