/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PayrollRun } from "./PayrollRun";
import { PayrollRunCountArgs } from "./PayrollRunCountArgs";
import { PayrollRunFindManyArgs } from "./PayrollRunFindManyArgs";
import { PayrollRunFindUniqueArgs } from "./PayrollRunFindUniqueArgs";
import { DeletePayrollRunArgs } from "./DeletePayrollRunArgs";
import { PayrollRunService } from "../payrollRun.service";
@graphql.Resolver(() => PayrollRun)
export class PayrollRunResolverBase {
  constructor(protected readonly service: PayrollRunService) {}

  async _payrollRunsMeta(
    @graphql.Args() args: PayrollRunCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PayrollRun])
  async payrollRuns(
    @graphql.Args() args: PayrollRunFindManyArgs
  ): Promise<PayrollRun[]> {
    return this.service.payrollRuns(args);
  }

  @graphql.Query(() => PayrollRun, { nullable: true })
  async payrollRun(
    @graphql.Args() args: PayrollRunFindUniqueArgs
  ): Promise<PayrollRun | null> {
    const result = await this.service.payrollRun(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PayrollRun)
  async deletePayrollRun(
    @graphql.Args() args: DeletePayrollRunArgs
  ): Promise<PayrollRun | null> {
    try {
      return await this.service.deletePayrollRun(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
